# What I'm doing in this script is just demonstrating reading and writing to .h5 files. Basically, I'm going to be reading an already
# existing .h5 file that was generated by Iris CC. I'll then copy these values and use them to create a new .h5 file called test



import h5py as h5 # This is the module I'm using for reading and writing
import numpy as np



with h5.File("C:/Users/deolu/OneDrive/Documents/Ligo/LIBS/autoTesting/Data for Sadia/powder_100ms_PDG_period_sample_moved_front_lower_exposure/2023-03-29T15-44-14_nr-050_speed_fast_distance_0_exposureUV_10000_exposureVisible_2500.001.h5") as f:
    print(f.keys())
    val = print(f['aux'])
    print(f['channel'])
    print(f['channelName'])
    print(f['frame'])
    print(f['intensity'])
    print(f['order'])
    print(f['saturationCount'])
    print(f['series'])
    print(f['settings'].keys())
    print(f['timeReceived'])
    print(f['timeReceivedLocal'])
    print(f['timeRecorded'])
    print(f['wavelength'])
    arr = f['intensity'][0][:]
    wavelength = f['wavelength'][:]

with h5.File("test1" '.h5', 'w') as f:
        f.create_group('aux')
        f.create_dataset('channel', data = [0, 1])
        f.create_dataset('channelName', data=[b'7213303SP',b'7213304SP'])
        f.create_dataset('frame', data=[0])
        f.create_dataset('intensity', data=arr)
        f.create_dataset('order', data=np.zeros(shape=(8188,1)))
        f.create_dataset('saturationCount', data=[0])
        f.create_dataset('series', data=[50])
        settings = f.create_group('settings')
        settings.create_dataset('exposureTime', data=[[10000],[2500]])
        settings.create_dataset('isAveraged', data=[0])
        settings.create_dataset('isDarkMeasurement', data=[0])
        settings.create_group('laser')
        f.create_dataset('timeReceived', data=[[1680129854923344],[1680129854916598]])
        f.create_dataset('timeReceivedLocal', data=[[1680104654923344],[1680104654916598]])
        f.create_dataset('timeRecorded', data=[[22393.30211],[22395.37896]])
        f.create_dataset('wavelength', data=wavelength)


        
