# What I'm doing in this script is just demonstrating reading and writing to .h5 files. Basically, I'm going to be reading an already
# existing .h5 file that was generated by Iris CC. I'll then copy these values and use them to generate a new .h5 file
# The values are technically hardcoded, but they are copied from the sample .h5 file. I didn't want to use variables because in the real
# application, we'd be building these files ourselves. The only times I used variables were for the wavelength and intensity frame groups
# since they were very long (Honestly now that I think about it, I could've just used a zero array). 



import h5py as h5 # This is the module I'm using for reading and writing
import numpy as np


# Reading in a sample .h5 file and printing out all the keys so that I know what to include in the manually generated file
with h5.File("2023-03-29T15-44-14_nr-050_speed_fast_distance_0_exposureUV_10000_exposureVisible_2500.001.h5") as f:
    print(f.keys())
    print(f['aux'])
    print(f['channel'])
    print(f['channel'][:])
    print(f['channelName'])
    print(f['channelName'][:])
    print(f['frame'])
    print(f['frame'][:])
    print(f['intensity'])
    print(f['intensity'][0][0:3])
    print(f['order'])
    print(f['order'][0:3])
    print(f['saturationCount'])
    print(f['saturationCount'][:])
    print(f['series'])
    print(f['series'][:])
    print(f['settings'].keys())
    print(f['settings']['exposureTime'][:][:])
    print(f['settings']['isAveraged'])
    print(f['settings']['isAveraged'][:])
    print(f['settings']['isDarkMeasurement'])
    print(f['settings']['isDarkMeasurement'][:])
    print(f['settings']['laser'])
    print(f['timeReceived'])
    print(f['timeReceived'][:][:])
    print(f['timeReceivedLocal'])
    print(f['timeReceivedLocal'][:][:])
    print(f['timeRecorded'])
    print(f['timeRecorded'][:][:])
    print(f['wavelength'])
    print(f['wavelength'][0:3])
    arr = f['intensity'][0][:] # Reading the intesity into a variable to be used in the manually generated file
    wavelength = f['wavelength'][:] # Reading the wavelength values into variable to be used in the manually generated file


# Creating our own .h5 file using the values that we got from the sample file 
with h5.File("test1" '.h5', 'w') as f:
        f.create_group('aux')
        f.create_dataset('channel', data = [0, 1])
        f.create_dataset('channelName', data=[b'7213303SP',b'7213304SP'])
        f.create_dataset('frame', data=[0])
        f.create_dataset('intensity', data=arr)
        f.create_dataset('order', data=np.zeros(shape=(8188,1)))
        f.create_dataset('saturationCount', data=[0])
        f.create_dataset('series', data=[50])
        settings = f.create_group('settings')
        settings.create_dataset('exposureTime', data=[[10000],[2500]])
        settings.create_dataset('isAveraged', data=[0])
        settings.create_dataset('isDarkMeasurement', data=[0])
        settings.create_group('laser')
        f.create_dataset('timeReceived', data=[[1680129854923344],[1680129854916598]])
        f.create_dataset('timeReceivedLocal', data=[[1680104654923344],[1680104654916598]])
        f.create_dataset('timeRecorded', data=[[22393.30211],[22395.37896]])
        f.create_dataset('wavelength', data=wavelength)


        
